description: Breaking down barriers for civil society
keywords: ""
images:
  - /media/uploads/about-hero.webp
favicon:
  color:
    mask: "#E28389"
    msapplication: "#E28389"
social:
  - name: linkedin
    url: https://www.linkedin.com/company/interalia-host/about/
contact:
  name: interalia gGmbH
  address: Rehlingstraße 9
  city_state_zip: 79100 Freiburg im Breisgau, Germany
  emails:
    - address: hello@interalia.host
      label: for general inquiries, press, and other information
  phone:
    number: +49 155 63208494
    label: office number
