name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'

    - name: Install dependencies
      run: |
        npm ci
        npm -g install js-beautify

    - name: Cache Hugo
      id: cache-hugo
      uses: actions/cache@v4
      with:
        path: ./hugo
        key: ${{ runner.os }}-hugo-0.145.0-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-hugo-0.145.0-

    - name: Install Hugo
      if: steps.cache-hugo.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_Linux-64bit.tar.gz
        tar -xzf hugo_extended_0.145.0_Linux-64bit.tar.gz hugo
        rm hugo_extended_0.145.0_Linux-64bit.tar.gz

    - name: Build Hugo site
      run: ./hugo -d public

    - name: Create CNAME file
      run: echo 'interalia.host' > public/CNAME

    - name: Beautify HTML files
      run: find public/ -type f -name "*.html" -exec js-beautify --html -r -m 1 "{}" \;

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public


